intrinsic fn default_output() -> AudioDevice = AudioDefaultOutput
intrinsic fn buffer_load_wav(path: Str) -> AudioBuffer = AudioBufferLoadWav
intrinsic fn buffer_frames(read buffer: AudioBuffer) -> Int = AudioBufferFrames
intrinsic fn buffer_channels(read buffer: AudioBuffer) -> Int = AudioBufferChannels
intrinsic fn buffer_sample_rate_hz(read buffer: AudioBuffer) -> Int = AudioBufferSampleRateHz
intrinsic fn play_buffer(read device: AudioDevice, read buffer: AudioBuffer) -> AudioPlayback = AudioPlayBuffer
intrinsic fn output_set_gain_milli(read device: AudioDevice, milli: Int) = AudioOutputSetGainMilli
intrinsic fn playback_stop(read playback: AudioPlayback) = AudioPlaybackStop
intrinsic fn playback_playing(read playback: AudioPlayback) -> Bool = AudioPlaybackPlaying
