name = "app"
kind = "app"

[deps]
arcana_desktop = { path = "../../../grimoires/owned/libs/arcana-desktop", native_child = "default" }
arcana_graphics = { path = "../../../grimoires/owned/libs/arcana-graphics" }
arcana_text = { path = "../../../grimoires/owned/libs/arcana-text", native_provider = "default" }
