authoritative_source = "Pinned Windows SDK metadata snapshot"
parity_target = "windows-sys"
env_var = "ARCANA_WINAPI_WINMD"
file_name = "Windows.Win32.winmd"
metadata_version = "Microsoft.Windows.SDK.Win32Metadata 63.0.31"
sha256 = "97D24CF1A9DC3E50782BBF1DBA0952BF6A025FA583D8B3AE6C5EF713B463C869"
cargo_registry_package = "windows-bindgen-0.66.0"
cargo_registry_relative_path = "default/Windows.Win32.winmd"
windows_sys_package = "windows-sys-0.61.2"
windows_sys_relative_root = "src/Windows/Win32"
