pub const FROZEN_HIR_NODE_KINDS: &[&str] = &[
    "Module",
    "SymbolTable",
    "Import",
    "Use",
    "Trait",
    "Record",
    "Enum",
    "Impl",
    "Function",
    "Behavior",
    "System",
    "Type",
    "PageRollup",
    "Expr",
    "Stmt",
    "Pattern",
];
