name = "app"
kind = "app"

[deps]
arcana_desktop = { path = "../../../grimoires/libs/arcana-desktop", native_child = "default" }
arcana_graphics = { path = "../../../grimoires/libs/arcana-graphics" }
arcana_text = { path = "../../../grimoires/libs/arcana-text" }
