#![allow(non_upper_case_globals)]

macro_rules! define_intrinsic_enum {
    ($name:ident { $($variant:ident),* $(,)? }) => {
        #[derive(Clone, Copy, Debug, PartialEq, Eq)]
        pub(crate) enum $name {
            $($variant),*
        }
    };
}

define_intrinsic_enum!(SystemIntrinsic {
    IoPrint,
    IoEprint,
    IoFlushStdout,
    IoFlushStderr,
    IoStdinReadLineTry,
    PackageAssetRootTry,
    StdTimeMonotonicNowMs,
    TimeMonotonicNowMs,
    TimeMonotonicNowNs,
});

define_intrinsic_enum!(ConcurrentIntrinsic {
    ConcurrentSleep,
    ConcurrentBehaviorStep,
    ConcurrentThreadId,
    ConcurrentTaskDone,
    ConcurrentTaskJoin,
    ConcurrentThreadDone,
    ConcurrentThreadJoin,
    ConcurrentChannelNew,
    ConcurrentChannelSend,
    ConcurrentChannelRecv,
    ConcurrentMutexNew,
    ConcurrentMutexTake,
    ConcurrentMutexPut,
    ConcurrentAtomicIntNew,
    ConcurrentAtomicIntLoad,
    ConcurrentAtomicIntStore,
    ConcurrentAtomicIntAdd,
    ConcurrentAtomicIntSub,
    ConcurrentAtomicIntSwap,
    ConcurrentAtomicBoolNew,
    ConcurrentAtomicBoolLoad,
    ConcurrentAtomicBoolStore,
    ConcurrentAtomicBoolSwap,
});

define_intrinsic_enum!(MemoryIntrinsic {
    MemoryArenaNew,
    MemoryArenaAlloc,
    MemoryArenaLen,
    MemoryArenaHas,
    MemoryArenaGet,
    MemoryArenaBorrowRead,
    MemoryArenaBorrowEdit,
    MemoryArenaSet,
    MemoryArenaRemove,
    MemoryArenaReset,
    MemoryFrameNew,
    MemoryFrameAlloc,
    MemoryFrameLen,
    MemoryFrameHas,
    MemoryFrameGet,
    MemoryFrameBorrowRead,
    MemoryFrameBorrowEdit,
    MemoryFrameSet,
    MemoryFrameReset,
    MemoryPoolNew,
    MemoryPoolAlloc,
    MemoryPoolLen,
    MemoryPoolHas,
    MemoryPoolGet,
    MemoryPoolBorrowRead,
    MemoryPoolBorrowEdit,
    MemoryPoolSet,
    MemoryPoolRemove,
    MemoryPoolReset,
    MemoryPoolLiveIds,
    MemoryPoolCompact,
    MemoryTempNew,
    MemoryTempAlloc,
    MemoryTempLen,
    MemoryTempHas,
    MemoryTempGet,
    MemoryTempBorrowRead,
    MemoryTempBorrowEdit,
    MemoryTempSet,
    MemoryTempReset,
    MemorySessionNew,
    MemorySessionAlloc,
    MemorySessionLen,
    MemorySessionHas,
    MemorySessionGet,
    MemorySessionBorrowRead,
    MemorySessionBorrowEdit,
    MemorySessionSet,
    MemorySessionReset,
    MemorySessionSeal,
    MemorySessionUnseal,
    MemorySessionIsSealed,
    MemorySessionLiveIds,
    MemoryRingNew,
    MemoryRingPush,
    MemoryRingTryPop,
    MemoryRingLen,
    MemoryRingHas,
    MemoryRingGet,
    MemoryRingBorrowRead,
    MemoryRingBorrowEdit,
    MemoryRingSet,
    MemoryRingReset,
    MemoryRingWindowRead,
    MemoryRingWindowEdit,
    MemorySlabNew,
    MemorySlabAlloc,
    MemorySlabLen,
    MemorySlabHas,
    MemorySlabGet,
    MemorySlabBorrowRead,
    MemorySlabBorrowEdit,
    MemorySlabSet,
    MemorySlabRemove,
    MemorySlabReset,
    MemorySlabSeal,
    MemorySlabUnseal,
    MemorySlabIsSealed,
    MemorySlabLiveIds,
    MemoryArrayViewRead,
    MemoryArrayViewEdit,
    MemoryBytesView,
    MemoryBytesViewEdit,
    MemoryMappedView,
    MemoryMappedViewEdit,
    MemoryStrView,
    MemoryViewLen,
    MemoryViewGet,
    MemoryViewSubview,
    MemoryEditViewLen,
    MemoryEditViewGet,
    MemoryEditViewSet,
    MemoryEditViewSubviewRead,
    MemoryEditViewSubviewEdit,
    MemoryByteViewLen,
    MemoryByteViewAt,
    MemoryByteViewSubview,
    MemoryByteViewToArray,
    MemoryByteEditViewLen,
    MemoryByteEditViewAt,
    MemoryByteEditViewSet,
    MemoryByteEditViewSubviewRead,
    MemoryByteEditViewSubviewEdit,
    MemoryByteEditViewToArray,
    MemoryStrViewLenBytes,
    MemoryStrViewByteAt,
    MemoryStrViewSubview,
    MemoryStrViewToStr,
});

define_intrinsic_enum!(TextIntrinsic {
    TextLenBytes,
    TextByteAt,
    TextSliceBytes,
    TextStartsWith,
    TextEndsWith,
    TextFind,
    TextContains,
    TextTrimStart,
    TextTrimEnd,
    TextTrim,
    TextSplit,
    TextJoin,
    TextRepeat,
    TextSplitLines,
    TextFromInt,
    TextToIntTry,
    BytesFromStrUtf8,
    BytesToStrUtf8,
    BytesLen,
    BytesAt,
    BytesSlice,
    BytesSha256Hex,
    BytesThaw,
    ByteBufferNew,
    ByteBufferLen,
    ByteBufferAt,
    ByteBufferSet,
    ByteBufferPush,
    ByteBufferFreeze,
    Utf16FromStr,
    Utf16ToStr,
    Utf16Len,
    Utf16At,
    Utf16Slice,
    Utf16Thaw,
    Utf16BufferNew,
    Utf16BufferLen,
    Utf16BufferAt,
    Utf16BufferSet,
    Utf16BufferPush,
    Utf16BufferFreeze,
});

define_intrinsic_enum!(CollectionsIntrinsic {
    OptionIsSome,
    OptionIsNone,
    OptionUnwrapOr,
    ResultOk,
    ResultErr,
    ResultIsOk,
    ResultIsErr,
    ResultUnwrapOr,
    ListNew,
    ListLen,
    ListIsEmpty,
    ListPush,
    ListPop,
    ListTryPopOr,
    ArrayNew,
    ArrayLen,
    ArrayFromList,
    ArrayToList,
    MapNew,
    MapLen,
    MapHas,
    MapGet,
    MapSet,
    MapRemove,
    MapTryGetOr,
});

define_intrinsic_enum!(EcsIntrinsic {
    EcsSetSingleton,
    EcsHasSingleton,
    EcsGetSingleton,
    EcsSpawn,
    EcsDespawn,
    EcsSetComponentAt,
    EcsHasComponentAt,
    EcsGetComponentAt,
    EcsRemoveComponentAt,
});

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum RuntimeIntrinsic {
    System(SystemIntrinsic),
    Concurrent(ConcurrentIntrinsic),
    Memory(MemoryIntrinsic),
    Text(TextIntrinsic),
    Collections(CollectionsIntrinsic),
    Ecs(EcsIntrinsic),
}

macro_rules! impl_intrinsic_domain {
    ($wrapper:ident => $domain:ident { $($variant:ident),* $(,)? }) => {
        impl From<$domain> for RuntimeIntrinsic {
            fn from(value: $domain) -> Self {
                Self::$wrapper(value)
            }
        }

        impl RuntimeIntrinsic {
            $(pub(crate) const $variant: Self = Self::$wrapper($domain::$variant);)*
        }
    };
}

impl_intrinsic_domain!(System => SystemIntrinsic {
    IoPrint,
    IoEprint,
    IoFlushStdout,
    IoFlushStderr,
    IoStdinReadLineTry,
    PackageAssetRootTry,
    StdTimeMonotonicNowMs,
    TimeMonotonicNowMs,
    TimeMonotonicNowNs,
});

impl_intrinsic_domain!(Concurrent => ConcurrentIntrinsic {
    ConcurrentSleep,
    ConcurrentBehaviorStep,
    ConcurrentThreadId,
    ConcurrentTaskDone,
    ConcurrentTaskJoin,
    ConcurrentThreadDone,
    ConcurrentThreadJoin,
    ConcurrentChannelNew,
    ConcurrentChannelSend,
    ConcurrentChannelRecv,
    ConcurrentMutexNew,
    ConcurrentMutexTake,
    ConcurrentMutexPut,
    ConcurrentAtomicIntNew,
    ConcurrentAtomicIntLoad,
    ConcurrentAtomicIntStore,
    ConcurrentAtomicIntAdd,
    ConcurrentAtomicIntSub,
    ConcurrentAtomicIntSwap,
    ConcurrentAtomicBoolNew,
    ConcurrentAtomicBoolLoad,
    ConcurrentAtomicBoolStore,
    ConcurrentAtomicBoolSwap,
});

impl_intrinsic_domain!(Memory => MemoryIntrinsic {
    MemoryArenaNew,
    MemoryArenaAlloc,
    MemoryArenaLen,
    MemoryArenaHas,
    MemoryArenaGet,
    MemoryArenaBorrowRead,
    MemoryArenaBorrowEdit,
    MemoryArenaSet,
    MemoryArenaRemove,
    MemoryArenaReset,
    MemoryFrameNew,
    MemoryFrameAlloc,
    MemoryFrameLen,
    MemoryFrameHas,
    MemoryFrameGet,
    MemoryFrameBorrowRead,
    MemoryFrameBorrowEdit,
    MemoryFrameSet,
    MemoryFrameReset,
    MemoryPoolNew,
    MemoryPoolAlloc,
    MemoryPoolLen,
    MemoryPoolHas,
    MemoryPoolGet,
    MemoryPoolBorrowRead,
    MemoryPoolBorrowEdit,
    MemoryPoolSet,
    MemoryPoolRemove,
    MemoryPoolReset,
    MemoryPoolLiveIds,
    MemoryPoolCompact,
    MemoryTempNew,
    MemoryTempAlloc,
    MemoryTempLen,
    MemoryTempHas,
    MemoryTempGet,
    MemoryTempBorrowRead,
    MemoryTempBorrowEdit,
    MemoryTempSet,
    MemoryTempReset,
    MemorySessionNew,
    MemorySessionAlloc,
    MemorySessionLen,
    MemorySessionHas,
    MemorySessionGet,
    MemorySessionBorrowRead,
    MemorySessionBorrowEdit,
    MemorySessionSet,
    MemorySessionReset,
    MemorySessionSeal,
    MemorySessionUnseal,
    MemorySessionIsSealed,
    MemorySessionLiveIds,
    MemoryRingNew,
    MemoryRingPush,
    MemoryRingTryPop,
    MemoryRingLen,
    MemoryRingHas,
    MemoryRingGet,
    MemoryRingBorrowRead,
    MemoryRingBorrowEdit,
    MemoryRingSet,
    MemoryRingReset,
    MemoryRingWindowRead,
    MemoryRingWindowEdit,
    MemorySlabNew,
    MemorySlabAlloc,
    MemorySlabLen,
    MemorySlabHas,
    MemorySlabGet,
    MemorySlabBorrowRead,
    MemorySlabBorrowEdit,
    MemorySlabSet,
    MemorySlabRemove,
    MemorySlabReset,
    MemorySlabSeal,
    MemorySlabUnseal,
    MemorySlabIsSealed,
    MemorySlabLiveIds,
    MemoryArrayViewRead,
    MemoryArrayViewEdit,
    MemoryBytesView,
    MemoryBytesViewEdit,
    MemoryMappedView,
    MemoryMappedViewEdit,
    MemoryStrView,
    MemoryViewLen,
    MemoryViewGet,
    MemoryViewSubview,
    MemoryEditViewLen,
    MemoryEditViewGet,
    MemoryEditViewSet,
    MemoryEditViewSubviewRead,
    MemoryEditViewSubviewEdit,
    MemoryByteViewLen,
    MemoryByteViewAt,
    MemoryByteViewSubview,
    MemoryByteViewToArray,
    MemoryByteEditViewLen,
    MemoryByteEditViewAt,
    MemoryByteEditViewSet,
    MemoryByteEditViewSubviewRead,
    MemoryByteEditViewSubviewEdit,
    MemoryByteEditViewToArray,
    MemoryStrViewLenBytes,
    MemoryStrViewByteAt,
    MemoryStrViewSubview,
    MemoryStrViewToStr,
});

impl_intrinsic_domain!(Text => TextIntrinsic {
    TextLenBytes,
    TextByteAt,
    TextSliceBytes,
    TextStartsWith,
    TextEndsWith,
    TextFind,
    TextContains,
    TextTrimStart,
    TextTrimEnd,
    TextTrim,
    TextSplit,
    TextJoin,
    TextRepeat,
    TextSplitLines,
    TextFromInt,
    TextToIntTry,
    BytesFromStrUtf8,
    BytesToStrUtf8,
    BytesLen,
    BytesAt,
    BytesSlice,
    BytesSha256Hex,
    BytesThaw,
    ByteBufferNew,
    ByteBufferLen,
    ByteBufferAt,
    ByteBufferSet,
    ByteBufferPush,
    ByteBufferFreeze,
    Utf16FromStr,
    Utf16ToStr,
    Utf16Len,
    Utf16At,
    Utf16Slice,
    Utf16Thaw,
    Utf16BufferNew,
    Utf16BufferLen,
    Utf16BufferAt,
    Utf16BufferSet,
    Utf16BufferPush,
    Utf16BufferFreeze,
});

impl_intrinsic_domain!(Collections => CollectionsIntrinsic {
    OptionIsSome,
    OptionIsNone,
    OptionUnwrapOr,
    ResultOk,
    ResultErr,
    ResultIsOk,
    ResultIsErr,
    ResultUnwrapOr,
    ListNew,
    ListLen,
    ListIsEmpty,
    ListPush,
    ListPop,
    ListTryPopOr,
    ArrayNew,
    ArrayLen,
    ArrayFromList,
    ArrayToList,
    MapNew,
    MapLen,
    MapHas,
    MapGet,
    MapSet,
    MapRemove,
    MapTryGetOr,
});

impl_intrinsic_domain!(Ecs => EcsIntrinsic {
    EcsSetSingleton,
    EcsHasSingleton,
    EcsGetSingleton,
    EcsSpawn,
    EcsDespawn,
    EcsSetComponentAt,
    EcsHasComponentAt,
    EcsGetComponentAt,
    EcsRemoveComponentAt,
});

pub(crate) fn edit_arg_indices(intrinsic: RuntimeIntrinsic) -> &'static [usize] {
    match intrinsic {
        RuntimeIntrinsic::Collections(
            CollectionsIntrinsic::ListPush
            | CollectionsIntrinsic::ListPop
            | CollectionsIntrinsic::ListTryPopOr
            | CollectionsIntrinsic::MapSet
            | CollectionsIntrinsic::MapRemove,
        ) => &[0],
        _ => &[],
    }
}

pub(crate) fn take_arg_indices(intrinsic: RuntimeIntrinsic) -> &'static [usize] {
    match intrinsic {
        RuntimeIntrinsic::Collections(CollectionsIntrinsic::ArrayFromList) => &[0],
        RuntimeIntrinsic::Concurrent(ConcurrentIntrinsic::ConcurrentMutexNew) => &[0],
        RuntimeIntrinsic::Ecs(EcsIntrinsic::EcsSetSingleton) => &[0],
        RuntimeIntrinsic::Collections(
            CollectionsIntrinsic::ListPush | CollectionsIntrinsic::ListTryPopOr,
        ) => &[1],
        RuntimeIntrinsic::Concurrent(
            ConcurrentIntrinsic::ConcurrentChannelSend | ConcurrentIntrinsic::ConcurrentMutexPut,
        ) => &[1],
        RuntimeIntrinsic::Memory(
            MemoryIntrinsic::MemoryArenaAlloc
            | MemoryIntrinsic::MemoryFrameAlloc
            | MemoryIntrinsic::MemoryPoolAlloc,
        ) => &[1],
        RuntimeIntrinsic::Ecs(EcsIntrinsic::EcsSetComponentAt) => &[1],
        RuntimeIntrinsic::Collections(
            CollectionsIntrinsic::MapSet | CollectionsIntrinsic::MapTryGetOr,
        ) => &[2],
        RuntimeIntrinsic::Memory(
            MemoryIntrinsic::MemoryArenaSet
            | MemoryIntrinsic::MemoryFrameSet
            | MemoryIntrinsic::MemoryPoolSet,
        ) => &[2],
        _ => &[],
    }
}
